// boilerplate code generated by protoc-gen-go-boilerplate.
package temp

import (
	temp "github.com/lcmaguire/protoc-gen-go-boilerplate/gen/temp"
)

// Service implements proto.ExampleAPI.
type Service struct {
	temp.UnimplementedExampleAPIServer
}
